"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Activity,
  BadgeIndianRupee,
  Crosshair,
  ShieldCheck,
  ShieldX,
  Target,
} from "lucide-react";
import { toast } from "sonner";
import { AttackLab } from "@/components/AttackLab";
import { CasesTable } from "@/components/CasesTable";
import {
  DetectionRateChart,
  FraudDistributionChart,
} from "@/components/DashboardCharts";
import { MetricCard } from "@/components/MetricCard";
import { ModelEvaluation } from "@/components/ModelEvaluation";
import { OrchestrationPanel } from "@/components/OrchestrationPanel";
import { SignalTicker } from "@/components/SignalTicker";
import { Sidebar } from "@/components/Sidebar";
import { SOCConsole } from "@/components/SOCConsole";

import {
  generateCustomers,
  generateFeedback,
  getCases,
  getTransactions,
  launchAttack,
  loadDashboardState,
  type LaunchAttackInput,
} from "@/lib/api";
import type { DashboardState, SimulationRun } from "@/lib/types";

const initialState: DashboardState = {
  customers: [],
  runs: [],
  transactions: [],
  cases: [],
  feedback: null,
  nextScenario: null,
};

function formatNumber(value: number) {
  return new Intl.NumberFormat("en-IN").format(Math.round(value));
}

export default function Home() {
  const [state, setState] = useState<DashboardState>(initialState);
  const [loading, setLoading] = useState(true);

  const latestRun = state.runs[0] ?? null;

  const metrics = useMemo(() => {
    const transactions = latestRun?.total_transactions ?? state.transactions.length;
    const blocked = state.cases.filter((item) => item.decision === "BLOCK" || item.decision === "VERIFY").length;
    const threats = state.cases.filter((item) => item.risk_level === "HIGH" || item.risk_level === "CRITICAL").length;
    const lossPrevented = state.cases.reduce((sum, item) => sum + item.risk_score * 72000, 0);

    return {
      transactions,
      blocked,
      threats,
      lossPrevented,
      detection: state.feedback ? `${Math.round(state.feedback.detection_rate * 100)}%` : "--",
    };
  }, [latestRun, state.cases, state.feedback, state.transactions.length]);

  async function refresh() {
    const snapshot = await loadDashboardState();
    setState((current) => ({
      ...snapshot,
      feedback: current.feedback,
      nextScenario: current.nextScenario,
    }));
  }

  async function onLaunch(input: LaunchAttackInput): Promise<SimulationRun> {
    const run = await launchAttack(input);
    const [transactions, cases] = await Promise.all([getTransactions(), getCases()]);
    const snapshot = await loadDashboardState();

    setState((current) => ({
      ...current,
      ...snapshot,
      transactions: transactions.transactions,
      cases: cases.cases,
      feedback: null,
      nextScenario: null,
    }));

    const generation = run.scenario?._generation;
    if (generation?.source === "local_fallback") {
      toast.warning("LLM unavailable. Scenario generated by the deterministic fallback.");
    } else if (generation?.source === "llm") {
      toast.success(`Live LLM scenario generated by ${generation.model}.`);
    } else {
      toast.success("Attack launched. Blue Team analysis completed.");
    }
    return run;
  }

  async function onFeedback() {
    const result = await generateFeedback();
    setState((current) => ({
      ...current,
      feedback: result.feedback,
      nextScenario: result.next_scenario,
    }));
    toast.success(`Adaptive mutation ready: ${result.feedback.recommended_mutation}`);
  }

  async function seedCustomers() {
    const result = await generateCustomers(100);
    const snapshot = await loadDashboardState();
    setState((current) => ({
      ...current,
      ...snapshot,
    }));
    toast.success(`${result.created} customers generated`);
  }

  useEffect(() => {
    loadDashboardState()
      .then(setState)
      .catch(() => {
        toast.error("FastAPI backend is not reachable on port 8000");
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="relative z-10 flex min-h-screen gap-4 p-4">
      <Sidebar />

      <main className="min-w-0 flex-1">
        <SignalTicker />

        <section id="dashboard" className="relative flex min-h-screen items-center overflow-hidden py-20 text-center">
          <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true">
            <div className="grid-fx absolute inset-0">
              <div className="scanline absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-purple/40 to-transparent" />
            </div>
            <div className="aurora-blob aurora-a left-[8%] top-[-10%] h-[420px] w-[560px] bg-purpledeep/25" />
            <div className="aurora-blob aurora-b right-[4%] top-[-6%] h-[380px] w-[520px] bg-purple/20" />
            <div className="aurora-blob aurora-c left-1/2 top-[8%] h-[340px] w-[600px] -translate-x-1/2 bg-[#4c1d95]/25" />
            <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-b from-transparent to-bg" />
          </div>

          <div className="relative mx-auto w-full max-w-[1200px]">
            <div className="mb-6 inline-flex items-center rounded-full border border-purple/25 bg-purple/[0.08] px-4 py-1.5 font-mono text-[12px] uppercase tracking-[0.14em] text-purple">
              Red Team · Blue Team · Adaptive Loop
            </div>
            <h1 className="text-gradient mx-auto max-w-[1200px] text-[54px] leading-[1.02] font-bold tracking-[-0.01em] [font-family:var(--font-display)] sm:text-[76px] lg:text-[104px]">
              Smart defence for every transaction
            </h1>
            <p className="text-mute mx-auto mt-6 max-w-[720px] text-base leading-relaxed sm:text-lg lg:text-xl">
              Red Team attacks, synthetic fraud streams, Blue Team model scoring,
              explainable cases, and adaptive feedback.
            </p>

            <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
              <button
                type="button"
                onClick={seedCustomers}
                className="rounded-lg border border-white/[0.09] bg-white/[0.03] px-5 py-3 text-sm text-mute transition hover:border-white/[0.15] hover:bg-white/[0.06] hover:text-ink"
              >
                Generate Customers
              </button>
              <button
                type="button"
                onClick={refresh}
                className="rounded-lg bg-ink px-5 py-3 text-sm font-medium text-bg transition hover:bg-[#e6e8ea]"
              >
                Refresh
              </button>
            </div>
          </div>
        </section>

        <section className="mt-6 grid gap-px overflow-hidden rounded-[14px] border border-white/[0.06] bg-white/[0.06] md:grid-cols-3 xl:grid-cols-5">
          <MetricCard
            label="Transactions Analyzed"
            value={loading ? "--" : formatNumber(metrics.transactions)}
            detail="Latest simulation stream"
            tone="cyan"
            icon={Activity}
          />
          <MetricCard
            label="Fraud Attempts Blocked"
            value={loading ? "--" : formatNumber(metrics.blocked)}
            detail="VERIFY and BLOCK decisions"
            tone="green"
            icon={ShieldCheck}
          />
          <MetricCard
            label="Potential Loss Prevented"
            value={`Rs ${formatNumber(metrics.lossPrevented)}`}
            detail="Estimated demo exposure"
            tone="amber"
            icon={BadgeIndianRupee}
          />
          <MetricCard
            label="Detection Accuracy"
            value={metrics.detection}
            detail="From feedback loop"
            tone="cyan"
            icon={Target}
          />
          <MetricCard
            label="Active Threats"
            value={loading ? "--" : formatNumber(metrics.threats)}
            detail="High and critical cases"
            tone="red"
            icon={ShieldX}
          />
        </section>

        <section className="mt-10">
          <SOCConsole />
        </section>

        <section className="mt-12 grid gap-5 xl:grid-cols-[1.4fr_0.8fr]">
          <article className="panel p-5">
            <div className="mb-5 flex items-center justify-between gap-3">
              <div>
                <span className="font-mono text-[11px] font-medium uppercase tracking-[0.1em] text-purple">
                  Main Dashboard
                </span>
                <h2 className="mt-2 text-xl font-semibold tracking-[-0.02em] text-ink md:text-[22px]">
                  Detection rate chart
                </h2>
              </div>
              <span className="rounded-full border border-up/25 bg-up/10 px-2.5 py-1 font-mono text-[10px] font-medium uppercase tracking-[0.1em] text-up">
                Live
              </span>
            </div>
            <DetectionRateChart
              cases={state.cases}
              transactions={state.transactions}
              feedback={state.feedback}
            />
          </article>

          <article className="panel p-5">
            <div>
              <span className="font-mono text-[11px] font-medium uppercase tracking-[0.1em] text-purple">
                Fraud Category Distribution
              </span>
              <h2 className="mt-2 text-xl font-semibold tracking-[-0.02em] text-ink md:text-[22px]">
                Synthetic traffic mix
              </h2>
            </div>
            <FraudDistributionChart transactions={state.transactions} />
          </article>
        </section>

        <ModelEvaluation transactions={state.transactions} />

        <section id="attack-lab" className="panel mt-12 p-5">
          <div className="mb-5 flex items-center gap-3">
            <div className="grid h-10 w-10 shrink-0 place-items-center rounded-[10px] border border-down/25 bg-down/10">
              <Crosshair className="h-5 w-5 text-down" />
            </div>
            <div>
              <h2 className="text-2xl font-semibold tracking-[-0.02em] text-ink md:text-[24px]">
                Red Team Lab
              </h2>
              <span className="mt-1 block font-mono text-[11px] font-medium uppercase tracking-[0.1em] text-dim">
                Pick attack type, volume, fraud percentage, and launch
              </span>
            </div>
          </div>
          <AttackLab onLaunch={onLaunch} />
        </section>

        <section id="orchestration" className="mt-12">
          <OrchestrationPanel
            run={latestRun}
            feedback={state.feedback}
            nextScenario={state.nextScenario}
            onFeedback={onFeedback}
          />
        </section>

        <section id="cases" className="panel mt-12 p-5">
          <div className="mb-5 flex items-center gap-3">
            <div className="grid h-10 w-10 shrink-0 place-items-center rounded-[10px] border border-[#38bdf8]/25 bg-[#38bdf8]/10">
              <ShieldCheck className="h-5 w-5 text-[#38bdf8]" />
            </div>
            <div>
              <h2 className="text-2xl font-semibold tracking-[-0.02em] text-ink md:text-[24px]">
                Blue Team Cases
              </h2>
              <span className="mt-1 block font-mono text-[11px] font-medium uppercase tracking-[0.1em] text-dim">
                Transaction table, risk score, decision, and explanation text
              </span>
            </div>
          </div>
          <CasesTable cases={state.cases} />
        </section>
      </main>
    </div>
  );
}
